apiVersion: v1
kind: Namespace
metadata:
  name: axiom
  labels:
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: axiom-monitoring
  labels:
    app.kubernetes.io/managed-by: kubectl
